import { FaFacebook, FaInstagram, FaTwitter } from 'react-icons/fa'

const menu = [
  {
    id: 1,
    title: 'Aries',
    category: 'blue merle',
    price: 1750.0,
    deposit: 550,
    img: './images/aries.jpeg',
    age: '',
    sex: 'female',
    goHomeDate: Date.now(),
    favToy: '',
    desc: `I'm baby woke mlkshk wolf bitters live-edge blue bottle, hammock freegan copper mug whatever cold-pressed `,
  },
  {
    id: 2,
    title: 'Kila',
    category: 'red tri',
    price: 1550.0,
    deposit: 450,
    img: './images/kila.jpeg',
    age: '',
    sex: 'female',
    goHomeDate: Date.now(),
    favToy: '',
    desc: `vaporware iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa thundercats `,
  },
  {
    id: 3,
    title: 'Lacie',
    category: 'blue merle',
    price: 1750.0,
    deposit: 550,
    img: './images/lacie.jpeg',
    age: '',
    sex: 'female',
    goHomeDate: Date.now(),
    favToy: '',
    desc: `ombucha chillwave fanny pack 3 wolf moon street art photo booth before they sold out organic viral.`,
  },
  {
    id: 4,
    title: 'Louie',
    category: 'black tri',
    price: 1550.0,
    deposit: 450,
    img: './images/louie.jpeg',
    age: '',
    sex: 'male',
    goHomeDate: Date.now(),
    favToy: '',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 6,
    title: 'Milo',
    category: 'red merle',
    price: 1750.0,
    deposit: 550,
    img: './images/milo.png',
    age: '',
    sex: 'male',
    goHomeDate: Date.now(),
    favToy: '',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'Orion',
    category: 'black tri',
    price: 1550.0,
    deposit: 450,
    img: './images/orion.jpeg',
    age: '',
    sex: 'male',
    goHomeDate: Date.now(),
    favToy: '',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'Hercules',
    category: 'red merle',
    price: 1750.0,
    deposit: 550,
    img: './images/perseus.jpeg',
    age: '',
    sex: 'male',
    goHomeDate: Date.now(),
    favToy: '',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
]

// data to map over for social links
const socialLinks = [
  {
    id: 1,
    url: 'https://www.facebook.com/annalipowiczart',
    icon: <FaFacebook />,
  },
  {
    id: 2,
    url: 'https://www.instagram.com/annalipowiczart/',
    icon: <FaInstagram />,
  },
  {
    id: 3,
    url: 'https://twitter.com/annalipowiczart',
    icon: <FaTwitter />,
  },
]
