# Generated by Django 4.1.7 on 2023-03-03 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
