# Generated by Django 4.1.7 on 2023-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_paintingphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='painting',
            name='year_created',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
