# Generated by Django 4.1.7 on 2023-03-03 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_painting_year_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='original_available',
            field=models.BooleanField(default=True),
        ),
    ]
