# Generated by Django 4.1.7 on 2023-03-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_painting_original_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='painting_subtype',
            field=models.CharField(blank=True, choices=[(None, 'No selection'), ('Winter', 'Winter'), ('France', 'France'), ('North America', 'North America'), ('Fall', 'Fall')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='painting',
            name='painting_type',
            field=models.CharField(blank=True, choices=[(None, 'No selection'), ('Landscape', 'Landscape'), ('Abstract', 'Abstract'), ('Flowers', 'Flowers'), ('Rainforest', 'Rainforest')], max_length=50, null=True),
        ),
    ]
