# Generated by Django 4.1.7 on 2023-03-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_painting_painting_subtype_painting_painting_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='painting',
            name='is_fall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='painting',
            name='is_spring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='painting',
            name='is_summer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='painting',
            name='is_winter',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_subtype',
            field=models.CharField(blank=True, choices=[(None, 'No selection'), ('France', 'France'), ('North America', 'North America')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='painting',
            name='painting_type',
            field=models.CharField(blank=True, choices=[(None, 'No selection'), ('Landscape', 'Landscape'), ('Abstract', 'Abstract'), ('Rainforest', 'Rainforest'), ('Flowers', 'Flowers')], max_length=50, null=True),
        ),
    ]
